version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: back/Dockerfile
      args:
        DB_URL: ${DB_URL}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_USERNAME: ${DB_USERNAME}
    environment:
        DB_URL: ${DB_URL}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_USERNAME: ${DB_USERNAME}
    ports:
      - "8080:8080"
  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
