version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: back/Dockerfile
      args:
        DB_URL: ${DB_URL}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_USERNAME: ${DB_USERNAME}
    environment:
        DB_URL: ${DB_URL}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_USERNAME: ${DB_USERNAME}
    ports:
      - "8080:8080"
  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    depends_on:
      - backend
    restart: always

  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
volumes:
  prometheus_data: {}
