spring:
  output:
    ansi:
      enabled: ALWAYS

  application:
    name: backend

  sql:
    init:
      mode: always
      encoding: UTF-8

  datasource:
    url: jdbc:postgresql://localhost:5432/Test
    username: postgres
    password: 15951 # 123
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect:  org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    defer-datasource-initialization: true