spring:
  output:
    ansi:
      enabled: ALWAYS

  application:
    name: backend

  sql:
    init:
      mode: always
      encoding: UTF-8

  datasource:
    url: jdbc:postgresql://${DB_HOST_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect:  org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

    show-sql: true
    hibernate:
      ddl-auto: update #create-drop
    open-in-view: true
    defer-datasource-initialization: true